In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(np.__version__)
print(type(arr))

[1 2 3 4]
2.1.2
<class 'numpy.ndarray'>


In [4]:
#create an array using a tupel

arr1=np.array((1,2,3,4,'Jasmeet'))
print(arr1)

['1' '2' '3' '4' 'Jasmeet']


In [8]:
# create a multidimensional array

arr1=np.array(55)
arr2=np.array([1,2,3,4,5])
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

55
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
0
1
2
3


In [9]:
#create a 5 dimension array 

arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('Dimension of an array is :',arr.ndim)


[[[[[1 2 3 4 5]]]]]
Dimension of an array is : 5


In [11]:
#accesing the np array element
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[5])

6


In [13]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1]+arr[4])

7


In [14]:
#accessing 2 dimensional array

arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,2])

3


In [15]:
#accessing 3 dimensional array

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,7]]])
print(arr[0,1,2])

6


In [17]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0:5])

[1 2 3 4 5]


In [18]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[2:6])

[3 4 5 6]


In [19]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[:6])

[1 2 3 4 5 6]


In [20]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,2:5])

[ 8  9 10]


In [21]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [23]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,0:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
arr=np.array([1.2,2.24,3.59])
newarr=arr.astype('int')

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [25]:
arr=np.array([1.2,2.24,3.59])
newarr=arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
arr=np.array([1,0,2.2])
newarr=arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [28]:
#copy and view if it is none then it owns the data otherwise if it shows the data means it doesn't owns the data

arr=np.array([1,2,3,4,5,6,7,8,9,10])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

None
[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
# shape of an array

arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [30]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=5)
print(arr)
print(arr.shape)

[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]
(1, 1, 1, 1, 10)


In [34]:
#Reshape an array

arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(5,2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [35]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
#reshape always returns a view because .base gives us the exact value not the none value 
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(arr.reshape(5,2).base)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [40]:
#flattening an array using reshape(-1)
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
